name: Automated Preprocessing Pipeline

on:
  push:
    branches: [ "main", "rpl" ]
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        pip install pandas numpy scikit-learn

    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_Rifa-Mardhatillah.py

    - name: Upload Processed Dataset
      uses: actions/upload-artifact@v4
      with:
        name: processed_dataset
        path: preprocessing/processed_dataset.csv
